device: "auto"

train:
  - _target_: src.metrics.NeuralMOS
    model_path: models/nisqa_mos_only.tar
    mode: predict_dir
    target_sr: 22050
    name: "NeuralMOS"

inference:
  - _target_: src.metrics.NeuralMOS
    model_path: models/nisqa_mos_only.tar
    mode: predict_dir
    target_sr: 22050
    name: "NeuralMOS"
