_target_: src.model.HiFiGAN
# generator
mel_channels: 80
hid_channels: 128
gen_kernels: [16, 16, 4, 4]
mrf_kernels: [3, 7, 11]
mrf_dilations: [[[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]]]
# discriminator
mpd_periods: [2, 3, 5, 7, 11]
mpd_num_layers: 5
msd_hid_channels: 16
msd_kernel_size: 41
msd_n_layers: 4
msd_stride: 4
msd_pools: [1, 2, 4]
# common
audio_channels: 1
relu_slope: 0.1
