defaults:
  - model: hifigan
  - writer: cometml
  - metrics: common
  - datasets: ljspeech
  - dataloader: common
  - transforms: common
  - _self_

g_optimizer:
  _target_: torch.optim.AdamW
  betas: [0.8, 0.99]
  lr: 2e-4
  weight_decay: 0.01
g_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
g_loss_function:
  _target_: src.loss.GeneratorLoss

d_optimizer:
  _target_: torch.optim.AdamW
  betas: [0.8, 0.99]
  lr: 2e-4
  weight_decay: 0.01
d_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
d_loss_function:
  _target_: src.loss.DiscriminatorLoss

trainer:
  log_step: 100
  n_epochs: 1000
  epoch_len: 500
  device_tensors: ["spec", "audio"]
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto
  override: False # if True, will override the previous run with the same name
  monitor: "max val_NeuralMOS" # "off" or "max/min metric_name"
  save_period: 50
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 42
