defaults:
  - model: hifigan
  - writer: cometml
  - metrics: example
  - datasets: ljspeech
  - dataloader: example
  - transforms: example
  - _self_

g_optimizer:
  _target_: torch.optim.AdamW
  betas: [0.8, 0.99]
  lr: 2e-4
  weight_decay: 0.01
g_lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.999
  step_size: ${trainer.epoch_len}
g_loss_function:
  _target_: src.loss.GeneratorLoss

d_optimizer:
  _target_: torch.optim.AdamW
  betas: [0.8, 0.99]
  lr: 2e-4
  weight_decay: 0.01
d_lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.999
  step_size: ${trainer.epoch_len}
d_loss_function:
  _target_: src.loss.DiscriminatorLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["spec", "audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 42
