defaults:
  - model: baseline
  - metrics: example
  - datasets: example_eval
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"]
  device: auto
  save_path: "example"
  seed: 1
  from_pretrained: "saved/model_best.pth"
