_target_: src.logger.CometMLWriter
project_name: "speech-synthesis"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["g_loss", "d_loss", "g_adv_loss", "g_fm_loss", "g_mel_loss"]
log_checkpoints: False
id_length: 32
