_target_: src.logger.WandBWriter
project_name: "pytorch_template"
entity: null
run_name: "testing"
mode: "online"
loss_names: ["loss"]
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8
